config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations'}
  devise_scope :user do get 'users/sign_out' => 'sessions#destroy'
  end

  resources :questions
  resources :categories

  root :to => "home#index"

  get 'q_in_cat_search' => 'categories#show'
  get 'cat_search' => 'categories#index'
  get 'make_quiz' => 'quizzes#make_quiz'
  get 'reload_quiz' => 'quizzes#reload_quiz'
  get 'update_user_score_in_category' => 'quizzes#update_user_score_in_category'
  get 'show_results' => 'quizzes#show_results'
  get '/users/profile' => 'users#show_profile'
  get '/users/achivement' => 'users#show_achivement'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :questions
	has_many :user_ranks
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    if(params.has_key?(:cat_title))
      @categories=Category.where('name like ?', '%'+params[:cat_title]+'%').paginate(:page => params[:page])
    else
      @categories = Category.paginate(:page => params[:page])
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category=Category.find(params[:id])

    if(params.has_key?(:score))
      puts "@@@@@@@@@@@@@@ # Create @@@@@@@@@@@@@@@@@@@@"
      UserRank.create(:user_id=>User.find_by_email(current_user.email).id.to_i,:category_id=>params[:id],:score=>params[:score].to_i)
    end
    puts User.find_by_email(current_user.email).id.to_i
    puts "@@@@@@@@@@@@@@ finished @@@@@@@@@@@@@@@@@@@@"
    @userrank= UserRank.find_by_category_id(params[:id])
    if(! @userrank.nil? )
      @userrank= UserRank.where(:category_id => params[:id]).order("score DESC").limit(4)
    end

    if(params.has_key?(:q_title))
      @questions=@category.questions.where('questionTitle like ?', '%'+params[:q_title]+'%').paginate(:page => params[:page], per_page: 15)
    else
      @questions=@category.questions.paginate(:page => params[:page], per_page: 15)
    end
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:image, :name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for @category, :html => { :class => "login" } do |f| %>

    <% if @category.errors.any? %>
      <div id="error_expl" class="panel panel-danger">
        <div class="panel-heading">
          <h3 class="panel-title"><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h3>
        </div>
        <div class="panel-body">
          <ul>
          <% @category.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      </div>
    <% end %>
    <div class="field">
      <%= f.text_field :name, autofocus: true, :placeholder => t(:name), :class => 'required form-control', :required => 'required' %>
    </div>
    <div class="field">
      <%= f.text_field :image, autofocus: true, :placeholder => t(:image), :class => 'required form-control', :required => 'required' %>
    </div>


  <%= f.submit "افزودن دسته بندی", :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            categories_path, :class => 'btn btn-default' %>

<% end %>

app/views/categories/edit.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => "ویرایش دسته", :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/categories/index.html.erb
<script>
$(document).ready(function(){
    $(".dropdown").hover(
        function() {
            $('.dropdown-menu', this).stop( true, true ).slideDown("fast");
            $(this).toggleClass('open');
        },
        function() {
            $('.dropdown-menu', this).stop( true, true ).slideUp("fast");
            $(this).toggleClass('open');
        }
    );
});
</script>
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => "دسته ها" %></h1>
</div>
  <div class="admission">
     <div class="container">
       <div class="faculty_top">
        <% @categories.each do |category| %>
            <div class="col-sm-3 faculty_grid">
              <figure class="team_member">
                <%= image_tag category.image, :class => "img-responsive wp-post-image", :alt => "" %>
                <div></div>
                <figcaption><h3 class="person-title"><%= link_to category.name, category %></h3>
                  <p></p>
                 </figcaption>
               </figure>
            </div>
        <% end %>

        <div class="clearfix"> </div>
    </div>
    <%= will_paginate @categories, :previous_label => t(:previous), :next_label => t(:next) %>
    </div>
  </div>


<%= link_to t('.new', :default => t("helpers.links.new")),
            new_category_path,
            :class => 'btn btn-primary' %>

app/views/categories/new.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'دسته بندی جدید'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/categories/show.html.erb
<script src="/assets/clientSocket.js"></script>

<div id="whole_category_container">

<div id="current_category_id_container" hidden><%= @category.id %></div>
<div id="current_user_id_container" hidden><%= current_user.id %></div>
<div id="other_user_id_container" hidden>0</div>

  <%- model_class = Category -%>
  <style>
    .user_rank {
      margin-right: auto;
      margin-left: auto;
      width: 300px;
    }

  </style>
<div class="page-header">
  <h1><%=t '.title', :default => "دسته بندی " + @category.name %></h1>
</div>
  <div class="row text-center">
    <div class="col-md-12">
      <%= form_tag q_in_cat_search_path, :method => :get do %>
          <%= text_field_tag :q_title, params[:q_title] %>
          <%= hidden_field_tag 'id', @category.id %>
          <%= submit_tag t(:question_search), :name => nil %>
      <% end %>
    </div>
  </div>
  <br>
  <div class="row text-center">
  <%= button_to "مسابقه آفلاین", '/make_quiz', :params => {:id => @category.id}, :class => "btn btn-primary btn-lg1",:method => :get  %>
	<br/>
	</div>
	<div class="row text-center">
	<button id='online_quizz_button' onclick="clientSocket.askForOnlineMatch();" class="btn btn-primary btn-lg1">مسابقه آنلاین</button>
  </div>
	<div class="row text-center">
		<div class="col col-md-2 col-md-offset-5">
			<%= image_tag '/assets/loading.gif', :class => "img-responsive wp-post-image", :alt => "", :id => 'loading_img' %>
		</div>
	</div>
  <% if ! @userrank.nil? then%>
      <div class="user_rank" >
  <table class="table" >
    <thead>
		<tr>قهرمانان</tr>
		<tr >
    <th class="text-right" ><%= "اسم" %></th>
    <th class="text-right"><%= "امتیاز" %></th>
    </tr>
    </thead>
    <tbody>

      <% @userrank.each do |userrank| %>
    <tr class="success">

          <td>  <%= userrank.user.firs_name%></td>
           <td><%= userrank.score%></td>

    </tr>
      <% end %>

    </tbody>
  </table>
      </div>
    <% end%>


<%= render 'questions/index' %>
<%= will_paginate @questions, :previous_label => t(:previous), :next_label => t(:next) %>

</div>